import type { Pool } from "pg";
import { randomUUID } from "node:crypto";
import type {
  AnalysisRunRecord, AuditEventRecord, BasePushRunRecord, BatchState,
  ModuleDictionaryVersionRecord, PersonMappingRecord, PmSnapshotRecord,
  PipelineJobRecord, PipelineJobType, PriorityLevel, PriorityRuleVersionRecord,
  RequirementRecord, SourceConfigRecord, SourceSnapshotRecord, SyncBatchRecord, SyncItemAction,
  SyncItemRecord, SyncTrigger,
} from "../../domain/persistence.js";
import type { AnalysisState, OwnerState, PullState, PushState } from "../../domain/workflow.js";
import { assertTransition } from "../../domain/transitions.js";
import type { SourceConfigUpdate } from "../../contracts/source.js";
import type {
  AnalysisRunRepository, AuditEventRepository, BasePushRunRepository,
  ModuleDictionaryRepository, PersonMappingRepository, PmSnapshotRepository,
  PipelineJobRepository, PriorityRuleRepository, RequirementQueryRepository,
  RequirementSearchCursor, SourceConfigRepository, SourceSnapshotRepository, SyncBatchRepository, SyncItemRepository,
} from "../../application/repositories.js";
import { encodeRequirementCursor } from "../../application/requirement-cursor.js";

export interface RequirementRowWrite {
  sourceConfigId: string;
  teambitionRequirementId: string;
  title: string;
  description: string | null;
  scope: string | null;
  acceptanceCriteria: string | null;
  proposerUserId: string | null;
  proposerName: string | null;
  executorUserId: string | null;
  executorName: string | null;
  statusId: string | null;
  createdAt: string | null;
  updatedAt: string | null;
  sourceUrl: string | null;
  uniqueId: number | null;
  attachmentRefs: string[];
  customFields: unknown[];
  payload: Record<string, unknown>;
  sourceHash: string;
  substantiveHash: string;
  sourceVersion: number;
  latestBatchId: string;
}

const requirement=(r:any):RequirementRecord=>({id:r.id,sourceConfigId:r.source_config_id,teambitionRequirementId:r.teambition_requirement_id,teambitionUniqueId:r.teambition_unique_id,title:r.title,description:r.description,scope:r.scope,acceptanceCriteria:r.acceptance_criteria,proposerUserId:r.proposer_user_id,proposerName:r.proposer_name,executorUserId:r.executor_user_id,executorName:r.executor_name,sourceStatusId:r.source_status_id,sourceCreatedAt:asDate(r.source_created_at),sourceUpdatedAt:asDate(r.source_updated_at),sourceUrl:r.source_url,attachmentRefs:r.attachment_refs,sourceCustomFields:r.source_custom_fields,sourcePayload:r.source_payload,sourceHash:r.source_hash,substantiveHash:r.substantive_hash,sourceVersion:Number(r.source_version),latestBatchId:r.latest_batch_id,baseRecordId:r.base_record_id,lastPushedAt:asDate(r.last_pushed_at),pipeline:{pull:r.pull_state,analysis:r.analysis_state,owner:r.owner_state,push:r.push_state},firstSeenAt:asDate(r.first_seen_at)!,lastSeenAt:asDate(r.last_seen_at)!,createdAt:asDate(r.created_at)!,updatedAt:asDate(r.updated_at)!});

const asDate=(v:Date|string|null):string|null=>v===null?null:new Date(v).toISOString();
const sourceConfig=(r:any):SourceConfigRecord=>({id:r.id,provider:r.provider,externalProjectId:r.external_project_id,externalProjectName:r.external_project_name,requirementTypeId:r.requirement_type_id,enabled:r.enabled,scheduleEnabled:r.schedule_enabled,scheduleWeekday:r.schedule_weekday,scheduleLocalTime:r.schedule_local_time,scheduleTimezone:r.schedule_timezone,ownerNames:r.owner_names,fieldMap:r.field_map,createdAt:asDate(r.created_at)!,updatedAt:asDate(r.updated_at)!});
const batch=(r:any):SyncBatchRecord=>({id:r.id,sourceConfigId:r.source_config_id,triggerType:r.trigger_type,actorId:r.actor_id,idempotencyKey:r.idempotency_key,status:r.status,startedAt:asDate(r.started_at)!,completedAt:asDate(r.completed_at),totalCount:r.total_count,succeededCount:r.succeeded_count,failedCount:r.failed_count,errorSummary:r.error_summary,createdAt:asDate(r.created_at)!});
const item=(r:any):SyncItemRecord=>({id:r.id,batchId:r.batch_id,requirementId:r.requirement_id,teambitionRequirementId:r.teambition_requirement_id,action:r.action,status:r.status,errorCode:r.error_code,errorDetail:r.error_detail,startedAt:asDate(r.started_at)!,completedAt:asDate(r.completed_at)});
const snapshot=(r:any):SourceSnapshotRecord=>({id:r.id,requirementId:r.requirement_id,sourceVersion:r.source_version,sourceHash:r.source_hash,substantiveHash:r.substantive_hash,payload:r.payload,isSubstantiveChange:r.is_substantive_change,capturedAt:asDate(r.captured_at)!});
const analysis=(r:any):AnalysisRunRecord=>({id:r.id,requirementId:r.requirement_id,sourceVersion:r.source_version,analysisVersion:r.analysis_version,status:r.status,moduleSuggestion:r.module_suggestion,confidence:r.confidence,confidenceReason:r.confidence_reason,priority:r.priority,structuredResult:r.structured_result,provider:r.provider,model:r.model,promptVersion:r.prompt_version,moduleDictionaryVersion:r.module_dictionary_version,priorityRuleVersionId:r.priority_rule_version_id,safeErrorCode:r.safe_error_code,safeErrorSummary:r.safe_error_summary,startedAt:asDate(r.started_at)!,completedAt:asDate(r.completed_at)});
const mapping=(r:any):PersonMappingRecord=>({id:r.id,sourceConfigId:r.source_config_id,teambitionUserId:r.teambition_user_id,teambitionDisplayName:r.teambition_display_name,normalizedName:r.normalized_name,feishuUserId:r.feishu_user_id,feishuIdType:r.feishu_id_type,matchMethod:r.match_method,active:r.active,createdBy:r.created_by,createdAt:asDate(r.created_at)!,updatedAt:asDate(r.updated_at)!});
const pmSnapshot=(r:any):PmSnapshotRecord=>({id:r.id,requirementId:r.requirement_id,sourceVersion:r.source_version,baseRecordId:r.base_record_id,pmValues:r.pm_values,capturedAt:asDate(r.captured_at)!});
const basePush=(r:any):BasePushRunRecord=>({id:r.id,requirementId:r.requirement_id,sourceVersion:r.source_version,pushVersion:r.push_version,status:r.status,idempotencyKey:r.idempotency_key,baseRecordId:r.base_record_id,safeErrorCode:r.safe_error_code,safeErrorSummary:r.safe_error_summary,startedAt:asDate(r.started_at)!,completedAt:asDate(r.completed_at)});
const job=(r:any):PipelineJobRecord=>({id:r.id,jobType:r.job_type,dedupeKey:r.dedupe_key,payload:r.payload,status:r.status,attemptCount:r.attempt_count,maxAttempts:r.max_attempts,availableAt:asDate(r.available_at)!,lockedUntil:asDate(r.locked_until),lastErrorCode:r.last_error_code,lastErrorSummary:r.last_error_summary,createdAt:asDate(r.created_at)!,updatedAt:asDate(r.updated_at)!});
const audit=(r:any):AuditEventRecord=>({id:r.id,actorId:r.actor_id,eventType:r.event_type,entityType:r.entity_type,entityId:r.entity_id,result:r.result,safeDetails:r.safe_details,occurredAt:asDate(r.occurred_at)!});
const dictionary=(r:any):ModuleDictionaryVersionRecord=>({version:r.version,status:r.status,entries:r.entries,createdBy:r.created_by,createdAt:asDate(r.created_at)!,publishedAt:asDate(r.published_at)});
const priorityRule=(r:any):PriorityRuleVersionRecord=>({id:r.id,version:r.version,status:r.status,rules:r.rules,validationEvidence:r.validation_evidence,createdBy:r.created_by,createdAt:asDate(r.created_at)!,publishedAt:asDate(r.published_at)});
export class ActiveBatchConflict extends Error{constructor(){super("An active batch already exists for this source");this.name="ActiveBatchConflict";}}
export class PostgresSourceConfigRepository implements SourceConfigRepository{constructor(private readonly pool:Pool){}async list(){const{rows}=await this.pool.query("SELECT * FROM source_configs ORDER BY created_at,id");return rows.map(sourceConfig);}async get(id:string){const{rows}=await this.pool.query("SELECT * FROM source_configs WHERE id=$1",[id]);return rows[0]?sourceConfig(rows[0]):null;}async update(id:string,u:SourceConfigUpdate){const{rows}=await this.pool.query("UPDATE source_configs SET external_project_id=$2,external_project_name=$3,requirement_type_id=$4,enabled=$5,schedule_enabled=$6,schedule_weekday=$7,schedule_local_time=$8,schedule_timezone=$9,owner_names=$10,field_map=$11,updated_at=now() WHERE id=$1 RETURNING *",[id,u.projectId,u.projectName,u.requirementTypeId,u.enabled,u.schedule.enabled,u.schedule.weekday,u.schedule.time,u.schedule.timezone,u.ownerNames,u.fieldMap]);return rows[0]?sourceConfig(rows[0]):null;}async create(p:{projectId:string;projectName:string;requirementTypeId:string;enabled:boolean}):Promise<SourceConfigRecord>{const{rows}=await this.pool.query("INSERT INTO source_configs(id,external_project_id,external_project_name,requirement_type_id,enabled) VALUES($1,$2,$3,$4,$5) RETURNING *",[randomUUID(),p.projectId,p.projectName,p.requirementTypeId,p.enabled]);return sourceConfig(rows[0]);}}
export class PostgresSyncBatchRepository implements SyncBatchRepository{constructor(private readonly pool:Pool){}async create(p:{sourceConfigId:string;triggerType:SyncTrigger;actorId:string|null;idempotencyKey:string;startedAt:string}){const c=await this.pool.connect();try{await c.query("BEGIN");await c.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[p.sourceConfigId]);const existing=await c.query("SELECT * FROM sync_batches WHERE source_config_id=$1 AND idempotency_key=$2",[p.sourceConfigId,p.idempotencyKey]);if(existing.rows[0]){await c.query("COMMIT");return batch(existing.rows[0]);}const active=await c.query("SELECT 1 FROM sync_batches WHERE source_config_id=$1 AND status='running' LIMIT 1",[p.sourceConfigId]);if(active.rowCount)throw new ActiveBatchConflict();const{rows}=await c.query("INSERT INTO sync_batches(id,source_config_id,trigger_type,actor_id,idempotency_key,started_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[randomUUID(),p.sourceConfigId,p.triggerType,p.actorId,p.idempotencyKey,p.startedAt]);await c.query("COMMIT");return batch(rows[0]);}catch(error){await c.query("ROLLBACK");throw error;}finally{c.release();}}async get(id:string){const{rows}=await this.pool.query("SELECT * FROM sync_batches WHERE id=$1",[id]);return rows[0]?batch(rows[0]):null;}async findByIdempotencyKey(s:string,k:string){const{rows}=await this.pool.query("SELECT * FROM sync_batches WHERE source_config_id=$1 AND idempotency_key=$2",[s,k]);return rows[0]?batch(rows[0]):null;}async list(q:{status?:BatchState;limit:number;cursor?:string}){const{rows}=await this.pool.query("SELECT * FROM sync_batches WHERE ($1::text IS NULL OR status=$1) AND ($2::timestamptz IS NULL OR started_at<$2) ORDER BY started_at DESC,id DESC LIMIT $3",[q.status??null,q.cursor??null,q.limit+1]);const more=rows.length>q.limit,page=rows.slice(0,q.limit);return{items:page.map(batch),nextCursor:more?asDate(page.at(-1)!.started_at):null};}async complete(id:string,r:{status:BatchState;totalCount:number;succeededCount:number;failedCount:number;errorSummary:string|null;completedAt:string}){const{rows}=await this.pool.query("UPDATE sync_batches SET status=$2,total_count=$3,succeeded_count=$4,failed_count=$5,error_summary=$6,completed_at=$7 WHERE id=$1 RETURNING *",[id,r.status,r.totalCount,r.succeededCount,r.failedCount,r.errorSummary,r.completedAt]);return rows[0]?batch(rows[0]):null;}}
export class PostgresSyncItemRepository implements SyncItemRepository{constructor(private readonly pool:Pool){}async upsert(p:{batchId:string;requirementId:string|null;teambitionRequirementId:string;action:SyncItemAction;status:"succeeded"|"failed";errorCode?:string;errorDetail?:string;startedAt:string;completedAt:string}){const{rows}=await this.pool.query("INSERT INTO sync_items(id,batch_id,requirement_id,teambition_requirement_id,action,status,error_code,error_detail,started_at,completed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(batch_id,teambition_requirement_id) DO UPDATE SET requirement_id=excluded.requirement_id,action=excluded.action,status=excluded.status,error_code=excluded.error_code,error_detail=excluded.error_detail,started_at=excluded.started_at,completed_at=excluded.completed_at /* A retry records its most recent orchestrator-measured start. */ RETURNING *",[randomUUID(),p.batchId,p.requirementId,p.teambitionRequirementId,p.action,p.status,p.errorCode??null,p.errorDetail??null,p.startedAt,p.completedAt]);return item(rows[0]);}async get(id:string){const{rows}=await this.pool.query("SELECT * FROM sync_items WHERE id=$1",[id]);return rows[0]?item(rows[0]):null;}async listByBatch(id:string){const{rows}=await this.pool.query("SELECT * FROM sync_items WHERE batch_id=$1 ORDER BY started_at,id",[id]);return rows.map(item);}}
export class PostgresSourceSnapshotRepository implements SourceSnapshotRepository{constructor(private readonly pool:Pool){}async append(p:{requirementId:string;sourceVersion:number;sourceHash:string;substantiveHash:string;payload:Record<string,unknown>;isSubstantiveChange:boolean;capturedAt:string}){const{rows}=await this.pool.query("INSERT INTO source_snapshots(id,requirement_id,source_version,source_hash,substantive_hash,payload,is_substantive_change,captured_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(requirement_id,source_version) DO NOTHING RETURNING *",[randomUUID(),p.requirementId,p.sourceVersion,p.sourceHash,p.substantiveHash,p.payload,p.isSubstantiveChange,p.capturedAt]);if(rows[0])return snapshot(rows[0]);const q=await this.pool.query("SELECT * FROM source_snapshots WHERE requirement_id=$1 AND source_version=$2",[p.requirementId,p.sourceVersion]);return snapshot(q.rows[0]);}async latest(id:string){const{rows}=await this.pool.query("SELECT * FROM source_snapshots WHERE requirement_id=$1 ORDER BY source_version DESC LIMIT 1",[id]);return rows[0]?snapshot(rows[0]):null;}}
export class PostgresRequirementRepository implements RequirementQueryRepository{constructor(private readonly pool:Pool){}async upsertRequirement(sourceConfigId:string,externalId:string,d:RequirementRowWrite){const c=await this.pool.connect();try{await c.query("BEGIN");const q=await c.query("SELECT id,source_version,source_hash FROM requirements WHERE source_config_id=$1 AND teambition_requirement_id=$2 FOR UPDATE",[sourceConfigId,externalId]);const old=q.rows[0],created=!old,id=old?.id??randomUUID(),hash=d.sourceHash,sub=d.substantiveHash,version=created?1:Number(old.source_version)+(old.source_hash===hash?0:1);await c.query("INSERT INTO requirements(id,source_config_id,teambition_requirement_id,teambition_unique_id,title,description,scope,acceptance_criteria,proposer_user_id,proposer_name,executor_user_id,executor_name,source_status_id,source_created_at,source_updated_at,source_url,attachment_refs,source_custom_fields,source_payload,source_hash,substantive_hash,source_version,latest_batch_id,pull_state,analysis_state,owner_state,push_state) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,'synced','pending','pending_mapping','pending') ON CONFLICT(source_config_id,teambition_requirement_id) DO UPDATE SET teambition_unique_id=excluded.teambition_unique_id,title=excluded.title,description=excluded.description,scope=excluded.scope,acceptance_criteria=excluded.acceptance_criteria,proposer_user_id=excluded.proposer_user_id,proposer_name=excluded.proposer_name,executor_user_id=excluded.executor_user_id,executor_name=excluded.executor_name,source_status_id=excluded.source_status_id,source_created_at=excluded.source_created_at,source_updated_at=excluded.source_updated_at,source_url=excluded.source_url,attachment_refs=excluded.attachment_refs,source_custom_fields=excluded.source_custom_fields,source_payload=excluded.source_payload,source_hash=excluded.source_hash,substantive_hash=excluded.substantive_hash,source_version=excluded.source_version,latest_batch_id=excluded.latest_batch_id,pull_state='synced',last_seen_at=now(),updated_at=now()",[id,sourceConfigId,externalId,d.uniqueId,d.title,d.description,d.scope,d.acceptanceCriteria,d.proposerUserId,d.proposerName,d.executorUserId,d.executorName,d.statusId,d.createdAt,d.updatedAt,d.sourceUrl,JSON.stringify(d.attachmentRefs),JSON.stringify(d.customFields),JSON.stringify(d.payload),hash,sub,version,d.latestBatchId]);await c.query("COMMIT");return{id,created,sourceVersion:version,sourceHash:hash,substantiveHash:sub};}catch(error){await c.query("ROLLBACK");throw error;}finally{c.release();}}
async get(id:string){const{rows}=await this.pool.query("SELECT * FROM requirements WHERE id=$1",[id]);return rows[0]?requirement(rows[0]):null;}
async findForSync(sourceConfigId:string,teambitionRequirementId:string){const{rows}=await this.pool.query("SELECT id,source_version,source_hash,substantive_hash FROM requirements WHERE source_config_id=$1 AND teambition_requirement_id=$2",[sourceConfigId,teambitionRequirementId]);return rows[0]?{id:String(rows[0].id),sourceVersion:Number(rows[0].source_version),sourceHash:String(rows[0].source_hash),substantiveHash:String(rows[0].substantive_hash)}:null;}
async search(q:{q?:string;pullState?:PullState;analysisState?:AnalysisState;ownerState?:OwnerState;pushState?:PushState;limit:number;cursor?:RequirementSearchCursor}){const values:unknown[]=[q.q??null,q.pullState??null,q.analysisState??null,q.ownerState??null,q.pushState??null];const cursorPredicate=q.cursor?" AND (created_at,id)<($6::timestamptz,$7::uuid)":"";if(q.cursor)values.push(q.cursor.createdAt,q.cursor.id);values.push(q.limit+1);const{rows}=await this.pool.query(`SELECT * FROM requirements WHERE ($1::text IS NULL OR title ILIKE '%'||$1||'%') AND ($2::text IS NULL OR pull_state=$2) AND ($3::text IS NULL OR analysis_state=$3) AND ($4::text IS NULL OR owner_state=$4) AND ($5::text IS NULL OR push_state=$5)${cursorPredicate} ORDER BY created_at DESC,id DESC LIMIT $${values.length}`,values);const more=rows.length>q.limit,page=rows.slice(0,q.limit);return{items:page.map(requirement),nextCursor:more?encodeRequirementCursor({createdAt:asDate(page.at(-1)!.created_at)!,id:String(page.at(-1)!.id)}):null};}
async updateAnalysisState(requirementId:string,to:AnalysisState){const{rows}=await this.pool.query("SELECT analysis_state FROM requirements WHERE id=$1",[requirementId]);if(!rows[0])throw new Error(`Requirement not found: ${requirementId}`);assertTransition("analysis",String(rows[0].analysis_state) as AnalysisState,to);await this.pool.query("UPDATE requirements SET analysis_state=$2,updated_at=now() WHERE id=$1",[requirementId,to]);}
async setOwner(requirementId:string,feishuUserId:string|null,state:OwnerState){const{rows}=await this.pool.query("SELECT owner_state FROM requirements WHERE id=$1",[requirementId]);if(!rows[0])throw new Error(`Requirement not found: ${requirementId}`);assertTransition("owner",String(rows[0].owner_state) as OwnerState,state);await this.pool.query("UPDATE requirements SET owner_state=$2,updated_at=now() WHERE id=$1",[requirementId,state]);}
async setBaseRecord(requirementId:string,baseRecordId:string,pushedAt:string){await this.pool.query("UPDATE requirements SET base_record_id=$2,last_pushed_at=$3,updated_at=now() WHERE id=$1",[requirementId,baseRecordId,pushedAt]);}
async setPushState(requirementId:string,state:PushState){const{rows}=await this.pool.query("SELECT push_state FROM requirements WHERE id=$1",[requirementId]);if(!rows[0])throw new Error(`Requirement not found: ${requirementId}`);assertTransition("push",String(rows[0].push_state) as PushState,state);await this.pool.query("UPDATE requirements SET push_state=$2,updated_at=now() WHERE id=$1",[requirementId,state]);}}
export { PostgresAnalysisRunRepository };
import { PostgresAnalysisRunRepository } from "./analysis-run-repository.js";

export class PostgresPersonMappingRepository implements PersonMappingRepository{constructor(private readonly pool:Pool){}async upsertManual(p:{sourceConfigId:string;teambitionUserId:string|null;teambitionDisplayName:string|null;feishuUserId:string;feishuIdType:"open_id"|"user_id"|"union_id";createdBy:string|null;now:string}){const normalized=p.teambitionDisplayName?.normalize("NFKC").trim().replace(/\s+/gu," ").toLocaleLowerCase()??null;const c=await this.pool.connect();try{await c.query("BEGIN");const existing=await c.query("SELECT * FROM person_mappings WHERE source_config_id=$1 AND active AND match_method='manual' AND teambition_user_id IS NOT DISTINCT FROM $2 AND feishu_user_id=$3 AND feishu_id_type=$4 LIMIT 1 FOR UPDATE",[p.sourceConfigId,p.teambitionUserId,p.feishuUserId,p.feishuIdType]);if(existing.rows[0]){await c.query("COMMIT");return mapping(existing.rows[0]);}await c.query("UPDATE person_mappings SET active=false,updated_at=$2 WHERE source_config_id=$1 AND active AND match_method='manual' AND teambition_user_id IS NOT DISTINCT FROM $3",[p.sourceConfigId,p.now,p.teambitionUserId]);const{rows}=await c.query("INSERT INTO person_mappings(id,source_config_id,teambition_user_id,teambition_display_name,normalized_name,feishu_user_id,feishu_id_type,match_method,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,'manual',$8,$9,$9) RETURNING *",[randomUUID(),p.sourceConfigId,p.teambitionUserId,p.teambitionDisplayName,normalized,p.feishuUserId,p.feishuIdType,p.createdBy,p.now]);await c.query("COMMIT");return mapping(rows[0]);}catch(error){await c.query("ROLLBACK");throw error;}finally{c.release();}}async resolveActive(s:string,b:{tbUserId?:string;normalizedName?:string}){const sql=b.tbUserId?"SELECT * FROM person_mappings WHERE source_config_id=$1 AND active AND teambition_user_id=$2":"SELECT * FROM person_mappings WHERE source_config_id=$1 AND active AND normalized_name=$2";const{rows}=await this.pool.query(sql,[s,b.tbUserId??b.normalizedName]);return rows.length===1?mapping(rows[0]):null;}async listActive(sourceConfigId:string){const{rows}=await this.pool.query("SELECT * FROM person_mappings WHERE source_config_id=$1 AND active ORDER BY updated_at DESC,id",[sourceConfigId]);return rows.map(mapping);}}
export class PostgresPmSnapshotRepository implements PmSnapshotRepository{constructor(private readonly pool:Pool){}async append(p:{requirementId:string;sourceVersion:number;baseRecordId:string;pmValues:Record<string,unknown>;capturedAt:string}){const{rows}=await this.pool.query("INSERT INTO pm_snapshots(id,requirement_id,source_version,base_record_id,pm_values,captured_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[randomUUID(),p.requirementId,p.sourceVersion,p.baseRecordId,p.pmValues,p.capturedAt]);return pmSnapshot(rows[0]);}async latest(id:string){const{rows}=await this.pool.query("SELECT * FROM pm_snapshots WHERE requirement_id=$1 ORDER BY source_version DESC,captured_at DESC LIMIT 1",[id]);return rows[0]?pmSnapshot(rows[0]):null;}}
export class PostgresBasePushRunRepository implements BasePushRunRepository{constructor(private readonly pool:Pool){}async append(p:{requirementId:string;sourceVersion:number;pushVersion:number;idempotencyKey:string;startedAt:string}){const{rows}=await this.pool.query("INSERT INTO base_push_runs(id,requirement_id,source_version,push_version,status,idempotency_key,started_at) VALUES($1,$2,$3,$4,'running',$5,$6) ON CONFLICT(idempotency_key) DO NOTHING RETURNING *",[randomUUID(),p.requirementId,p.sourceVersion,p.pushVersion,p.idempotencyKey,p.startedAt]);if(rows[0])return basePush(rows[0]);const q=await this.pool.query("SELECT * FROM base_push_runs WHERE idempotency_key=$1",[p.idempotencyKey]);return basePush(q.rows[0]);}async findByIdempotencyKey(key:string){const{rows}=await this.pool.query("SELECT * FROM base_push_runs WHERE idempotency_key=$1",[key]);return rows[0]?basePush(rows[0]):null;}async latest(requirementId:string){const{rows}=await this.pool.query("SELECT * FROM base_push_runs WHERE requirement_id=$1 ORDER BY started_at DESC,id DESC LIMIT 1",[requirementId]);return rows[0]?basePush(rows[0]):null;}async updateResult(id:string,r:{status:"pushed"|"failed";baseRecordId?:string;safeErrorCode?:string;safeErrorSummary?:string;completedAt:string}){const{rows}=await this.pool.query("UPDATE base_push_runs SET status=$2,base_record_id=$3,safe_error_code=$4,safe_error_summary=$5,completed_at=$6 WHERE id=$1 RETURNING *",[id,r.status,r.baseRecordId??null,r.safeErrorCode??null,r.safeErrorSummary??null,r.completedAt]);return rows[0]?basePush(rows[0]):null;}}
export class PostgresPipelineJobRepository implements PipelineJobRepository{constructor(private readonly pool:Pool){}async enqueue(p:{jobType:PipelineJobType;dedupeKey:string;payload:Record<string,unknown>;availableAt:string;maxAttempts?:number}){const{rows}=await this.pool.query("INSERT INTO pipeline_jobs(id,job_type,dedupe_key,payload,available_at,max_attempts) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(dedupe_key) DO UPDATE SET dedupe_key=excluded.dedupe_key RETURNING *",[randomUUID(),p.jobType,p.dedupeKey,p.payload,p.availableAt,p.maxAttempts??5]);return job(rows[0]);}async claimNext(_worker:string,lease:number,now:string){const c=await this.pool.connect();try{await c.query("BEGIN");const{rows}=await c.query("SELECT id FROM pipeline_jobs WHERE ((status='queued' AND available_at <= $1) OR (status='running' AND locked_until <= $1)) AND attempt_count<max_attempts ORDER BY available_at,created_at FOR UPDATE SKIP LOCKED LIMIT 1",[now]);if(!rows[0]){await c.query("COMMIT");return null;}const claimed=await c.query("UPDATE pipeline_jobs SET status='running',attempt_count=attempt_count+1,locked_until=$2::timestamptz + ($3::text||' milliseconds')::interval,updated_at=$2 WHERE id=$1 RETURNING *",[rows[0].id,now,lease]);await c.query("COMMIT");return job(claimed.rows[0]);}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}async reschedule(id:string,r:{expectedAttempt:number;backoffMs:number;errorCode?:string;errorSummary?:string;now:string}){const{rows}=await this.pool.query("UPDATE pipeline_jobs SET status='queued',available_at=$2::timestamptz + ($3::text||' milliseconds')::interval,locked_until=NULL,last_error_code=$4,last_error_summary=$5,updated_at=$2 WHERE id=$1 AND status='running' AND attempt_count=$6 RETURNING *",[id,r.now,String(r.backoffMs),r.errorCode??null,r.errorSummary??null,r.expectedAttempt]);return rows[0]?job(rows[0]):null;}async complete(id:string,r:{expectedAttempt:number;status:"succeeded"|"failed"|"cancelled";errorCode?:string;errorSummary?:string;now:string}){const{rows}=await this.pool.query("UPDATE pipeline_jobs SET status=$2,last_error_code=$3,last_error_summary=$4,locked_until=NULL,updated_at=$5 WHERE id=$1 AND status='running' AND attempt_count=$6 RETURNING *",[id,r.status,r.errorCode??null,r.errorSummary??null,r.now,r.expectedAttempt]);return rows[0]?job(rows[0]):null;}}
export class PostgresAuditEventRepository implements AuditEventRepository{constructor(private readonly pool:Pool){}async append(e:AuditEventRecord){await this.pool.query("INSERT INTO audit_events(id,actor_id,event_type,entity_type,entity_id,result,safe_details,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[e.id,e.actorId,e.eventType,e.entityType,e.entityId,e.result,e.safeDetails,e.occurredAt]);}async search(q:{entityId?:string;since?:string;until?:string;limit:number}){const{rows}=await this.pool.query("SELECT * FROM audit_events WHERE ($1::text IS NULL OR entity_id=$1) AND ($2::timestamptz IS NULL OR occurred_at >= $2) AND ($3::timestamptz IS NULL OR occurred_at <= $3) ORDER BY occurred_at DESC,id DESC LIMIT $4",[q.entityId??null,q.since??null,q.until??null,q.limit]);return rows.map(audit);}}
export class PostgresModuleDictionaryRepository implements ModuleDictionaryRepository{constructor(private readonly pool:Pool){}async list(){const{rows}=await this.pool.query("SELECT * FROM module_dictionary_versions ORDER BY version DESC");return rows.map(dictionary);}async get(v:number){const{rows}=await this.pool.query("SELECT * FROM module_dictionary_versions WHERE version=$1",[v]);return rows[0]?dictionary(rows[0]):null;}async create(p:{entries:unknown[];createdBy:string;now:string}){const c=await this.pool.connect();try{await c.query("BEGIN");await c.query("SELECT pg_advisory_xact_lock(hashtextextended('module_dictionary_versions',0))");const{rows}=await c.query("INSERT INTO module_dictionary_versions(version,status,entries,created_by,created_at) SELECT COALESCE(MAX(version),0)+1,'draft',$1,$2,$3 FROM module_dictionary_versions RETURNING *",[JSON.stringify(p.entries),p.createdBy,p.now]);await c.query("COMMIT");return dictionary(rows[0]!);}catch(error){await c.query("ROLLBACK");throw error;}finally{c.release();}}async publish(v:number,publishedAt:string){const c=await this.pool.connect();try{await c.query("BEGIN");await c.query("SELECT pg_advisory_xact_lock(hashtextextended('module_dictionary_versions',0))");await c.query("UPDATE module_dictionary_versions SET status='retired' WHERE status='published' AND version<>$1",[v]);const{rows}=await c.query("UPDATE module_dictionary_versions SET status='published',published_at=$2 WHERE version=$1 AND status='draft' RETURNING *",[v,publishedAt]);if(!rows[0])throw new Error("Dictionary publish requires an existing draft version");await c.query("COMMIT");return dictionary(rows[0]);}catch(error){await c.query("ROLLBACK");throw error;}finally{c.release();}}}
export class PostgresPriorityRuleRepository implements PriorityRuleRepository{constructor(private readonly pool:Pool){}async get(id:string){const{rows}=await this.pool.query("SELECT * FROM priority_rule_versions WHERE id=$1",[id]);return rows[0]?priorityRule(rows[0]):null;}async getPublished(){const{rows}=await this.pool.query("SELECT * FROM priority_rule_versions WHERE status='published' ORDER BY version DESC LIMIT 1");return rows[0]?priorityRule(rows[0]):null;}async list(){const{rows}=await this.pool.query("SELECT * FROM priority_rule_versions ORDER BY version DESC");return rows.map(priorityRule);}async create(p:{rules:Record<string,unknown>;validationEvidence:unknown[];createdBy:string;now:string}){const c=await this.pool.connect();try{await c.query("BEGIN");await c.query("SELECT pg_advisory_xact_lock(hashtextextended('priority_rule_versions',0))");const{rows}=await c.query("INSERT INTO priority_rule_versions(id,version,status,rules,validation_evidence,created_by,created_at) SELECT $1,COALESCE(MAX(version),0)+1,'draft',$2,$3,$4,$5 FROM priority_rule_versions RETURNING *",[randomUUID(),JSON.stringify(p.rules),JSON.stringify(p.validationEvidence),p.createdBy,p.now]);await c.query("COMMIT");return priorityRule(rows[0]!);}catch(error){await c.query("ROLLBACK");throw error;}finally{c.release();}}async publish(id:string,publishedAt:string){const c=await this.pool.connect();try{await c.query("BEGIN");await c.query("SELECT pg_advisory_xact_lock(hashtextextended('priority_rule_versions',0))");await c.query("UPDATE priority_rule_versions SET status='retired' WHERE status='published' AND id<>$1",[id]);const{rows}=await c.query("UPDATE priority_rule_versions SET status='published',published_at=$2 WHERE id=$1 AND status='draft' RETURNING *",[id,publishedAt]);if(!rows[0])throw new Error("Priority rule publish requires an existing draft version");await c.query("COMMIT");return priorityRule(rows[0]);}catch(error){await c.query("ROLLBACK");throw error;}finally{c.release();}}}
export class PostgresRepositories{readonly sources:PostgresSourceConfigRepository;readonly batches:PostgresSyncBatchRepository;readonly items:PostgresSyncItemRepository;readonly audit:PostgresAuditEventRepository;readonly jobs:PostgresPipelineJobRepository;readonly sourceSnapshots:PostgresSourceSnapshotRepository;readonly requirements:PostgresRequirementRepository;readonly analyses:PostgresAnalysisRunRepository;readonly people:PostgresPersonMappingRepository;readonly pmSnapshots:PostgresPmSnapshotRepository;readonly basePushes:PostgresBasePushRunRepository;readonly dictionaries:PostgresModuleDictionaryRepository;readonly priorityRules:PostgresPriorityRuleRepository;constructor(pool:Pool){this.sources=new PostgresSourceConfigRepository(pool);this.batches=new PostgresSyncBatchRepository(pool);this.items=new PostgresSyncItemRepository(pool);this.audit=new PostgresAuditEventRepository(pool);this.jobs=new PostgresPipelineJobRepository(pool);this.sourceSnapshots=new PostgresSourceSnapshotRepository(pool);this.requirements=new PostgresRequirementRepository(pool);this.analyses=new PostgresAnalysisRunRepository(pool);this.people=new PostgresPersonMappingRepository(pool);this.pmSnapshots=new PostgresPmSnapshotRepository(pool);this.basePushes=new PostgresBasePushRunRepository(pool);this.dictionaries=new PostgresModuleDictionaryRepository(pool);this.priorityRules=new PostgresPriorityRuleRepository(pool);}}
