import test from "node:test";
import assert from "node:assert/strict";
import { Pool } from "pg";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { PostgresRepositories } from "./repositories.js";

const root=resolve(dirname(fileURLToPath(import.meta.url)),"../../../../../");
async function getDatabaseUrl(){if(process.env.DATABASE_URL)return process.env.DATABASE_URL;const env=await readFile(resolve(root,".env"),"utf8").catch(()=>"");const value=env.match(/^DATABASE_URL=(.+)$/m)?.[1]?.trim();if(!value)throw new Error("PostgreSQL integration tests require DATABASE_URL in environment or repo .env");return value;}
async function setup(){const connectionString=await getDatabaseUrl();const admin=new Pool({connectionString,connectionTimeoutMillis:5000});const schema=`rq_test_${randomUUID().replaceAll("-","")}`;await admin.query(`CREATE SCHEMA "${schema}"`);const pool=new Pool({connectionString,options:`-c search_path=${schema}`,max:5});try{const sql=await readFile(resolve(root,"database/migrations/0001_initial.sql"),"utf8");await pool.query(sql);return{pool,admin,schema,repos:new PostgresRepositories(pool as never)};}catch(error){await pool.end();await admin.query(`DROP SCHEMA "${schema}" CASCADE`);await admin.end();throw error;}}
async function cleanup(ctx:{pool:Pool;admin:Pool;schema:string}){await ctx.pool.end();await ctx.admin.query(`DROP SCHEMA "${ctx.schema}" CASCADE`);await ctx.admin.end();}
const config={projectId:"tb-project",projectName:"Product",requirementTypeId:"req-type",enabled:true};
test("source configuration create/get persists and maps fields",async()=>{const ctx=await setup();try{const created=await ctx.repos.sources.createSource(config);assert.equal(created.externalProjectId,"tb-project");assert.equal((await ctx.repos.sources.get(created.id))?.requirementTypeId,"req-type");}finally{await cleanup(ctx);}});
test("sync batch create is idempotent and blocks a parallel active batch",async()=>{const ctx=await setup();try{const source=await ctx.repos.sources.createSource(config);const p={sourceConfigId:source.id,triggerType:"manual" as const,actorId:null,idempotencyKey:"manual-key-0001",startedAt:"2026-10-08T00:00:00Z"};const one=await ctx.repos.batches.create(p);assert.equal((await ctx.repos.batches.create(p)).id,one.id);await assert.rejects(()=>ctx.repos.batches.create({...p,idempotencyKey:"manual-key-0002"}),{name:"ActiveBatchConflict"});}finally{await cleanup(ctx);}});
test("persistent job queue claims a lease and completes the job",async()=>{const ctx=await setup();try{const job=await ctx.repos.jobs.enqueue({jobType:"sync",dedupeKey:"job-1",payload:{sourceId:"s"},availableAt:"2026-10-08T00:00:00Z"});const claimed=await ctx.repos.jobs.claimNext("worker",30000,"2026-10-08T00:00:01Z");assert.equal(claimed?.id,job.id);assert.equal(claimed?.attemptCount,1);assert.equal((await ctx.repos.jobs.complete(job.id,{status:"succeeded",now:"2026-10-08T00:00:02Z"}))?.status,"succeeded");}finally{await cleanup(ctx);}});
test("analysis records append versions and keep the earlier run",async()=>{const ctx=await setup();try{const s=await ctx.repos.sources.createSource(config);const r=await ctx.repos.requirements.upsertRequirement(s.id,"task-1",{sourceHash:"a".repeat(64),substantiveHash:"b".repeat(64),title:"A"});const a=await ctx.repos.analyses.append({requirementId:r.id,sourceVersion:1,analysisVersion:1,startedAt:"2026-10-08T00:00:00Z"});await ctx.repos.analyses.complete(a.id,{status:"failed_retryable",safeErrorCode:"PROVIDER_TIMEOUT",completedAt:"2026-10-08T00:00:01Z"});const b=await ctx.repos.analyses.append({requirementId:r.id,sourceVersion:1,analysisVersion:2,startedAt:"2026-10-08T00:00:02Z"});assert.equal((await ctx.repos.analyses.listByRequirement(r.id)).length,2);assert.equal((await ctx.repos.analyses.latest(r.id))?.id,b.id);}finally{await cleanup(ctx);}});
test("PM snapshots and audit events persist and can be read",async()=>{const ctx=await setup();try{const s=await ctx.repos.sources.createSource(config);const r=await ctx.repos.requirements.upsertRequirement(s.id,"task-1",{sourceHash:"c".repeat(64),substantiveHash:"d".repeat(64),title:"B"});await ctx.repos.pmSnapshots.append({requirementId:r.id,sourceVersion:1,baseRecordId:"rec-1",pmValues:{status:"待处理"},capturedAt:"2026-10-08T00:00:00Z"});assert.equal((await ctx.repos.pmSnapshots.latest(r.id))?.baseRecordId,"rec-1");await ctx.repos.audit.append({id:"00000000-0000-4000-8000-000000000001",actorId:null,eventType:"sync",entityType:"requirement",entityId:r.id,result:"succeeded",safeDetails:{},occurredAt:"2026-10-08T00:00:00Z"});assert.equal((await ctx.repos.audit.search({entityId:r.id,limit:5})).length,1);}finally{await cleanup(ctx);}});
