import test from "node:test";
import assert from "node:assert/strict";
import { Pool } from "pg";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { PostgresRepositories } from "./repositories.js";

const root=resolve(dirname(fileURLToPath(import.meta.url)),"../../../../../");
async function getDatabaseUrl(){if(process.env.DATABASE_URL)return process.env.DATABASE_URL;const env=await readFile(resolve(root,".env"),"utf8").catch(()=>"");const value=env.match(/^DATABASE_URL=(.+)$/m)?.[1]?.trim();if(!value)throw new Error("PostgreSQL integration tests require DATABASE_URL in environment or repo .env");return value;}
async function setup(){const connectionString=await getDatabaseUrl();const admin=new Pool({connectionString,connectionTimeoutMillis:5000});const schema=`rq_test_${randomUUID().replaceAll("-","")}`;await admin.query(`CREATE SCHEMA "${schema}"`);const pool=new Pool({connectionString,options:`-c search_path=${schema}`,max:5});try{const sql=await readFile(resolve(root,"database/migrations/0001_initial.sql"),"utf8");await pool.query(sql);const next=await readFile(resolve(root,"database/migrations/0002_single_source_config.sql"),"utf8");await pool.query(next);return{pool,admin,schema,repos:new PostgresRepositories(pool as never)};}catch(error){await pool.end();await admin.query(`DROP SCHEMA "${schema}" CASCADE`);await admin.end();throw error;}}
async function cleanup(ctx:{pool:Pool;admin:Pool;schema:string}){await ctx.pool.end();await ctx.admin.query(`DROP SCHEMA "${ctx.schema}" CASCADE`);await ctx.admin.end();}
const config={projectId:"tb-project",projectName:"Product",requirementTypeId:"req-type",enabled:true,schedule:{enabled:true,weekday:1,time:"09:30",timezone:"Asia/Shanghai"},ownerNames:["PM Owner"],fieldMap:{description:"cf-description"}};
function requirementWrite(sourceConfigId:string, latestBatchId:string, overrides:Partial<import("./repositories.js").RequirementRowWrite>={}) {
  return { sourceConfigId, teambitionRequirementId:"task-1", title:"Requirement", description:null, scope:null, acceptanceCriteria:null, proposerUserId:null, proposerName:null, executorUserId:null, executorName:null, statusId:null, createdAt:null, updatedAt:null, sourceUrl:null, uniqueId:null, attachmentRefs:[], customFields:[], payload:{}, sourceHash:"a".repeat(64), substantiveHash:"b".repeat(64), sourceVersion:1, latestBatchId, ...overrides };
}
test("source configuration create/get persists schedule, owner names and field map",async()=>{const ctx=await setup();try{const created=await ctx.repos.sources.create(config);assert.equal(created.externalProjectId,"tb-project");assert.equal((await ctx.repos.sources.get(created.id))?.requirementTypeId,"req-type");assert.equal(created.scheduleEnabled,true);assert.equal(created.scheduleWeekday,1);assert.equal(created.scheduleLocalTime,"09:30:00");assert.equal(created.scheduleTimezone,"Asia/Shanghai");assert.deepEqual(created.ownerNames,["PM Owner"]);assert.deepEqual(created.fieldMap,{description:"cf-description"});}finally{await cleanup(ctx);}});
test("source config mutation and audit append share one transaction",async()=>{const ctx=await setup();try{const source=await ctx.repos.sources.create(config);const event={id:"00000000-0000-4000-8000-000000000111",actorId:null,eventType:"source.updated",entityType:"source_config",entityId:source.id,result:"succeeded" as const,safeDetails:{},occurredAt:"2026-10-08T00:00:00Z"};await ctx.repos.audit.append(event);await assert.rejects(()=>ctx.repos.sources.update(source.id,{projectId:"changed",projectName:"Changed",requirementTypeId:"req-type",enabled:true,schedule:{enabled:false,weekday:null,time:null,timezone:null},ownerNames:[],fieldMap:{}},event));assert.equal((await ctx.repos.sources.get(source.id))?.externalProjectId,config.projectId);}finally{await cleanup(ctx);}});
test("MVP source configuration is database-enforced as a singleton",async()=>{const ctx=await setup();try{await ctx.repos.sources.create(config);await assert.rejects(()=>ctx.repos.sources.create({...config,projectId:"another-project"}),{code:"23505"});}finally{await cleanup(ctx);}});
test("sync batch create is idempotent and blocks a parallel active batch",async()=>{const ctx=await setup();try{const source=await ctx.repos.sources.create(config);const p={sourceConfigId:source.id,triggerType:"manual" as const,actorId:null,idempotencyKey:"manual-key-0001",startedAt:"2026-10-08T00:00:00Z"};const one=await ctx.repos.batches.create(p);assert.equal((await ctx.repos.batches.create(p)).id,one.id);await assert.rejects(()=>ctx.repos.batches.create({...p,idempotencyKey:"manual-key-0002"}),{name:"ActiveBatchConflict"});}finally{await cleanup(ctx);}});
test("persistent job queue claims a lease and completes the job with fencing",async()=>{const ctx=await setup();try{const job=await ctx.repos.jobs.enqueue({jobType:"sync",dedupeKey:"job-1",payload:{sourceId:"s"},availableAt:"2026-10-08T00:00:00Z"});const claimed=await ctx.repos.jobs.claimNext("worker",30000,"2026-10-08T00:00:01Z");assert.equal(claimed?.id,job.id);assert.equal(claimed?.attemptCount,1);const stale=await ctx.repos.jobs.claimNext("worker-b",30000,"2026-10-08T00:00:35Z");assert.equal(stale?.attemptCount,2);assert.equal(await ctx.repos.jobs.complete(job.id,{expectedAttempt:1,status:"succeeded",now:"2026-10-08T00:00:40Z"}),null);const recovered=await ctx.repos.jobs.complete(job.id,{expectedAttempt:2,status:"succeeded",now:"2026-10-08T00:00:40Z"});assert.equal(recovered?.status,"succeeded");}finally{await cleanup(ctx);}});
test("analysis records append versions and keep the earlier run",async()=>{const ctx=await setup();try{const s=await ctx.repos.sources.create(config);const syncBatch=await ctx.repos.batches.create({sourceConfigId:s.id,triggerType:"manual",actorId:null,idempotencyKey:"analysis-requirement-0001",startedAt:"2026-10-08T00:00:00Z"});const r=await ctx.repos.requirements.upsertRequirement(s.id,"task-1",requirementWrite(s.id,syncBatch.id,{title:"A"}));const a=await ctx.repos.analyses.append({requirementId:r.id,sourceVersion:1,analysisVersion:1,startedAt:"2026-10-08T00:00:00Z"});await ctx.repos.analyses.complete(a.id,{status:"failed_retryable",safeErrorCode:"PROVIDER_TIMEOUT",completedAt:"2026-10-08T00:00:01Z"});const b=await ctx.repos.analyses.append({requirementId:r.id,sourceVersion:1,analysisVersion:2,startedAt:"2026-10-08T00:00:02Z"});assert.equal((await ctx.repos.analyses.listByRequirement(r.id)).length,2);assert.equal((await ctx.repos.analyses.latest(r.id))?.id,b.id);}finally{await cleanup(ctx);}});
test("analysis completion rejects a result produced for a stale source version",async()=>{const ctx=await setup();try{const s=await ctx.repos.sources.create(config);const b=await ctx.repos.batches.create({sourceConfigId:s.id,triggerType:"manual",actorId:null,idempotencyKey:"analysis-stale-0001",startedAt:"2026-10-08T00:00:00Z"});const r=await ctx.repos.requirements.upsertRequirement(s.id,"task-stale",requirementWrite(s.id,b.id,{teambitionRequirementId:"task-stale"}));const run=await ctx.repos.analyses.append({requirementId:r.id,sourceVersion:1,analysisVersion:1,startedAt:"2026-10-08T00:00:01Z"});await ctx.repos.requirements.upsertRequirement(s.id,"task-stale",requirementWrite(s.id,b.id,{teambitionRequirementId:"task-stale",sourceHash:"e".repeat(64),sourceVersion:2}));assert.equal(await ctx.repos.analyses.complete(run.id,{status:"analyzed",completedAt:"2026-10-08T00:00:02Z"}),null);}finally{await cleanup(ctx);}});
test("PM snapshots and audit events persist and can be read",async()=>{const ctx=await setup();try{const s=await ctx.repos.sources.create(config);const b=await ctx.repos.batches.create({sourceConfigId:s.id,triggerType:"manual",actorId:null,idempotencyKey:"snapshot-requirement-0001",startedAt:"2026-10-08T00:00:00Z"});const r=await ctx.repos.requirements.upsertRequirement(s.id,"task-1",requirementWrite(s.id,b.id,{sourceHash:"c".repeat(64),substantiveHash:"d".repeat(64),title:"B"}));await ctx.repos.pmSnapshots.append({requirementId:r.id,sourceVersion:1,baseRecordId:"rec-1",pmValues:{status:"待处理"},capturedAt:"2026-10-08T00:00:00Z"});assert.equal((await ctx.repos.pmSnapshots.latest(r.id))?.baseRecordId,"rec-1");await ctx.repos.audit.append({id:"00000000-0000-4000-8000-000000000001",actorId:null,eventType:"sync",entityType:"requirement",entityId:r.id,result:"succeeded",safeDetails:{},occurredAt:"2026-10-08T00:00:00Z"});assert.equal((await ctx.repos.audit.search({entityId:r.id,limit:5})).length,1);}finally{await cleanup(ctx);}});

test("requirement upsert round-trips source URL and latest batch",async()=>{const ctx=await setup();try{const source=await ctx.repos.sources.create(config);const batch=await ctx.repos.batches.create({sourceConfigId:source.id,triggerType:"manual",actorId:null,idempotencyKey:"requirement-url-0001",startedAt:"2026-10-08T00:00:00Z"});const created=await ctx.repos.requirements.upsertRequirement(source.id,"task-url",requirementWrite(source.id,batch.id,{teambitionRequirementId:"task-url",sourceUrl:"https://example.test/requirements/task-url"}));const persisted=await ctx.repos.requirements.get(created.id);assert.equal(persisted?.sourceUrl,"https://example.test/requirements/task-url");assert.equal(persisted?.latestBatchId,batch.id);}finally{await cleanup(ctx);}});
test("requirement search keyset cursor returns a second page",async()=>{const ctx=await setup();try{const source=await ctx.repos.sources.create(config);const batch=await ctx.repos.batches.create({sourceConfigId:source.id,triggerType:"manual",actorId:null,idempotencyKey:"search-cursor-0001",startedAt:"2026-10-08T00:00:00Z"});for(const id of ["one","two","three"]){await ctx.pool.query("INSERT INTO requirements(id,source_config_id,teambition_requirement_id,title,source_hash,substantive_hash,latest_batch_id,created_at) VALUES($1,$2,$3,$3,$4,$5,$6,$7)",[randomUUID(),source.id,id,"a".repeat(64),"b".repeat(64),batch.id,"2026-10-08T00:00:00Z"]);}const first=await ctx.repos.requirements.search({limit:1});assert.equal(first.items.length,1);assert.ok(first.nextCursor);const { decodeRequirementCursor }=await import("../../application/requirement-cursor.js");const second=await ctx.repos.requirements.search({limit:1,cursor:decodeRequirementCursor(first.nextCursor)!});assert.equal(second.items.length,1);assert.notEqual(second.items[0]?.id,first.items[0]?.id);}finally{await cleanup(ctx);}});
test("batch keyset cursor does not skip rows with identical start times and applies inclusive time filters",async()=>{const ctx=await setup();try{const source=await ctx.repos.sources.create(config);const ids:string[]=[];for(let i=0;i<3;i++){const batch=await ctx.repos.batches.create({sourceConfigId:source.id,triggerType:"manual",actorId:null,idempotencyKey:`same-time-batch-${i}`,startedAt:"2026-10-08T00:00:00Z"});ids.push(batch.id);await ctx.repos.batches.complete(batch.id,{status:"succeeded",totalCount:0,succeededCount:0,failedCount:0,errorSummary:null,completedAt:"2026-10-08T00:00:01Z"});}const first=await ctx.repos.batches.list({since:"2026-10-08T00:00:00Z",until:"2026-10-08T00:00:00Z",limit:1});assert.equal(first.items.length,1);assert.ok(first.nextCursor);const {decodeBatchCursor}=await import("../../application/batch-cursor.js");const second=await ctx.repos.batches.list({since:"2026-10-08T00:00:00Z",until:"2026-10-08T00:00:00Z",limit:1,cursor:decodeBatchCursor(first.nextCursor)!});assert.equal(second.items.length,1);assert.notEqual(second.items[0]?.id,first.items[0]?.id);assert.equal(ids.length,3);}finally{await cleanup(ctx);}});

test("changed source upsert atomically snapshots, resets analysis and push, and only clears owner mapping when the TB owner changes",async()=>{
  const ctx=await setup();
  try{
    const source=await ctx.repos.sources.create(config);
    const batch1=await ctx.repos.batches.create({sourceConfigId:source.id,triggerType:"manual",actorId:null,idempotencyKey:"source-version-0001",startedAt:"2026-10-08T00:00:00Z"});
    const first=await ctx.repos.requirements.upsertRequirement(source.id,"task-owner",requirementWrite(source.id,batch1.id,{teambitionRequirementId:"task-owner",executorUserId:"tb-owner-1",executorName:"Ada",snapshot:{payload:{version:1},isSubstantiveChange:false,capturedAt:"2026-10-08T00:00:00Z"}}));
    await ctx.repos.batches.complete(batch1.id,{status:"succeeded",totalCount:1,succeededCount:1,failedCount:0,errorSummary:null,completedAt:"2026-10-08T00:00:01Z"});
    await ctx.repos.requirements.setOwner(first.id,"ou-owner-1","manually_mapped");
    await ctx.repos.requirements.updateAnalysisState(first.id,"running");await ctx.repos.requirements.updateAnalysisState(first.id,"analyzed");
    await ctx.repos.requirements.setPushState(first.id,"running");await ctx.repos.requirements.setPushState(first.id,"pushed");
    const batch2=await ctx.repos.batches.create({sourceConfigId:source.id,triggerType:"manual",actorId:null,idempotencyKey:"source-version-0002",startedAt:"2026-10-09T00:00:00Z"});
    const second=await ctx.repos.requirements.upsertRequirement(source.id,"task-owner",requirementWrite(source.id,batch2.id,{teambitionRequirementId:"task-owner",executorUserId:"tb-owner-1",executorName:"Ada",sourceHash:"c".repeat(64),sourceVersion:2,snapshot:{payload:{version:2},isSubstantiveChange:true,capturedAt:"2026-10-09T00:00:00Z"}}));
    await ctx.repos.batches.complete(batch2.id,{status:"succeeded",totalCount:1,succeededCount:1,failedCount:0,errorSummary:null,completedAt:"2026-10-09T00:00:01Z"});
    const afterContentUpdate=await ctx.repos.requirements.get(second.id);
    assert.equal(afterContentUpdate?.pipeline.analysis,"pending");assert.equal(afterContentUpdate?.pipeline.push,"pending");assert.equal(afterContentUpdate?.pipeline.owner,"manually_mapped");
    assert.equal((await ctx.repos.sourceSnapshots.latest(second.id))?.sourceVersion,2);
    const batch3=await ctx.repos.batches.create({sourceConfigId:source.id,triggerType:"manual",actorId:null,idempotencyKey:"source-version-0003",startedAt:"2026-10-10T00:00:00Z"});
    await ctx.repos.requirements.upsertRequirement(source.id,"task-owner",requirementWrite(source.id,batch3.id,{teambitionRequirementId:"task-owner",executorUserId:"tb-owner-2",executorName:"Bea",sourceHash:"d".repeat(64),sourceVersion:3,snapshot:{payload:{version:3},isSubstantiveChange:false,capturedAt:"2026-10-10T00:00:00Z"}}));
    assert.equal((await ctx.repos.requirements.get(second.id))?.pipeline.owner,"pending_mapping");
    assert.equal((await ctx.repos.sourceSnapshots.latest(second.id))?.sourceVersion,3);
  }finally{await cleanup(ctx);}
});
test("sync item persists orchestrator started time",async()=>{const ctx=await setup();try{const source=await ctx.repos.sources.create(config);const batch=await ctx.repos.batches.create({sourceConfigId:source.id,triggerType:"manual",actorId:null,idempotencyKey:"item-start-0001",startedAt:"2026-10-08T00:00:00Z"});const wrote=await ctx.repos.items.upsert({batchId:batch.id,requirementId:null,teambitionRequirementId:"task-start",action:"created",status:"succeeded",startedAt:"2026-10-08T00:00:05Z",completedAt:"2026-10-08T00:00:10Z"});assert.equal(wrote.startedAt,"2026-10-08T00:00:05.000Z");}finally{await cleanup(ctx);}});
